version: '3.8'
services:
  db:
   image: mysql:8
   container_name: tiendaPerritos
   restart: always
   enviroment:
      MYSQL_DATABASE: tienda_perritos
      MYSQL_ROOT_PASSWORD: admin123
   ports:
    - "3306:3306"

  backend:
    images:
    container_name:
    restart: always
    ports:
    - "3001:3001"
    depend_on:
    - db
    environment:
      - DB_HOST: db
      - DB_PORT: 3306
  
  web:
    image: 
    container_name:
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend